# Generated by Django 3.0.4 on 2020-05-13 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อหมวดหมู่')),
                ('content', models.TextField(default='ใส่เนื้อหาบทความ')),
                ('slug', models.SlugField(default='ใส่ลิงค์บทความ ตัวอย่าง /your-post-content', max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.TextField(default='ใส่ชื่อเว็บไซต์')),
                ('sitedescription', models.TextField(default='ใส่รายละเอียดเว็บไซต์')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_images', models.ImageField(default='media/noimg-l.jpg', upload_to='')),
                ('title', models.CharField(default='ใส่ชื่อบทความ', max_length=200, unique=True)),
                ('content', models.TextField(default='ใส่เนื้อหาบทความ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('post_viewcount', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(default='ใส่ลิงค์บทความ ตัวอย่าง /your-post-content', max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
