# Generated by Django 3.0.4 on 2020-05-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_images',
            field=models.ImageField(upload_to='media'),
        ),
    ]
