# Generated by Django 3.0.5 on 2020-04-27 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_somemodeladmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SomeModelAdmin',
            new_name='PostAdmin',
        ),
    ]
