# Generated by Django 3.0.5 on 2020-04-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200427_2323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostAdmin',
        ),
    ]
