# Generated by Django 3.0.5 on 2020-04-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_postadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_images',
            field=models.ImageField(default='Choose Your Images', upload_to=''),
        ),
    ]
