# Generated by Django 3.0.5 on 2020-05-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_content_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.TextField(default='ใส่ชื่อเว็บไซต์')),
                ('sitedescription', models.TextField(default='ใส่รายละเอียดเว็บไซต์')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='ใส่เนื้อหาบทความ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_images',
            field=models.ImageField(default='media/noimg-l.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='ใส่ลิงค์บทความ ตัวอย่าง /your-post-content', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='ใส่ชื่อบทความ', max_length=200, unique=True),
        ),
    ]
